config/routes.rb
Rails.application.routes.draw do
  match '/contacts',     to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :cargos
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks"  }
  root to: "pages#home"

  resources :politicos do
      collection do
        match 'search' => 'politicos#search', via: [:get, :post], as: :search
      end
      member do
        put "like", to: "politicos#upvote"
        put "dislike", to: "politicos#downvote"
      end
      resources :comentarios do
        member do
              put "like", to: "comentarios#upvote"
              put "dislike", to: "comentarios#downvote"
        end
      end
      resources :acontecimentos do
        member do
          put "like", to: "acontecimentos#upvote"
          put "dislike", to: "acontecimentos#downvote"
        end
      end
  end
  
  resources :partidos
  
  get '/politicos/cargos/:nome' => 'politicos#show'
  get '/politicos/cargos/:nome/:estado' => 'politicos#show'
  get '/politicos/:id' => 'politicos#show'
  
  get 'mapa'=> 'pages#mapa'
  get 'not_found'=> 'pages#not_found'
  
  get '401'=> 'pages#not_found'
  get '404'=> 'pages#not_found'
  get '422'=> 'pages#not_found'
  get '500'=> 'pages#not_found'
  

end

app/models/cargo.rb
class Cargo < ActiveRecord::Base
    has_many :politicos
end

app/controllers/cargos_controller.rb
class CargosController < ApplicationController
  before_action :set_cargo, only: [:show, :edit, :update, :destroy]

  # GET /cargos
  # GET /cargos.json
  def index
    @cargos = Cargo.all
  end

  # GET /cargos/1
  # GET /cargos/1.json
  def show
  end

  # GET /cargos/new
  def new
    @cargo = Cargo.new
  end

  # GET /cargos/1/edit
  def edit
  end

  # POST /cargos
  # POST /cargos.json
  def create
    @cargo = Cargo.new(cargo_params)

    respond_to do |format|
      if @cargo.save
        format.html { redirect_to @cargo, notice: 'Cargo was successfully created.' }
        format.json { render :show, status: :created, location: @cargo }
      else
        format.html { render :new }
        format.json { render json: @cargo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cargos/1
  # PATCH/PUT /cargos/1.json
  def update
    respond_to do |format|
      if @cargo.update(cargo_params)
        format.html { redirect_to @cargo, notice: 'Cargo was successfully updated.' }
        format.json { render :show, status: :ok, location: @cargo }
      else
        format.html { render :edit }
        format.json { render json: @cargo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cargos/1
  # DELETE /cargos/1.json
  def destroy
    @cargo.destroy
    respond_to do |format|
      format.html { redirect_to cargos_url, notice: 'Cargo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cargo
      if (params[:nome])  
          @cargo = Cargo.where(nome: params[:nome]).first
        else
          @cargo = Cargo.find(params[:id])
      end
      
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cargo_params
      params.require(:cargo).permit(:nome, :salario, :funcao)
    end
end

app/helpers/cargos_helper.rb
module CargosHelper
end

app/views/cargos/_form.html.erb
<%= form_for(@cargo) do |f| %>
  <% if @cargo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cargo.errors.count, "error") %> prohibited this cargo from being saved:</h2>

      <ul>
      <% @cargo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :salario %><br>
    <%= f.text_field :salario %>
  </div>
  <div class="field">
    <%= f.label :funcao %><br>
    <%= f.text_field :funcao %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cargos/edit.html.erb
<h1>Editing Cargo</h1>

<%= render 'form' %>

<%= link_to 'Show', @cargo %> |
<%= link_to 'Back', cargos_path %>

app/views/cargos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cargos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Salario</th>
      <th>Funcao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cargos.each do |cargo| %>
      <tr>
        <td><%= cargo.nome %></td>
        <td><%= cargo.salario %></td>
        <td><%= cargo.funcao %></td>
        <td><%= link_to 'Show', cargo %></td>
        <td><%= link_to 'Edit', edit_cargo_path(cargo) %></td>
        <td><%= link_to 'Destroy', cargo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cargo', new_cargo_path %>

app/views/cargos/new.html.erb
<h1>New Cargo</h1>

<%= render 'form' %>

<%= link_to 'Back', cargos_path %>

app/views/cargos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @cargo.nome %>
</p>

<p>
  <strong>Salario:</strong>
  <%= @cargo.salario %>
</p>

<p>
  <strong>Funcao:</strong>
  <%= @cargo.funcao %>
</p>

<%= link_to 'Edit', edit_cargo_path(@cargo) %> |
<%= link_to 'Back', cargos_path %>