config/routes.rb
Rails.application.routes.draw do
  match '/contacts',     to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :cargos
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks"  }
  root to: "pages#home"

  resources :politicos do
      collection do
        match 'search' => 'politicos#search', via: [:get, :post], as: :search
      end
      member do
        put "like", to: "politicos#upvote"
        put "dislike", to: "politicos#downvote"
      end
      resources :comentarios do
        member do
              put "like", to: "comentarios#upvote"
              put "dislike", to: "comentarios#downvote"
        end
      end
      resources :acontecimentos do
        member do
          put "like", to: "acontecimentos#upvote"
          put "dislike", to: "acontecimentos#downvote"
        end
      end
  end
  
  resources :partidos
  
  get '/politicos/cargos/:nome' => 'politicos#show'
  get '/politicos/cargos/:nome/:estado' => 'politicos#show'
  get '/politicos/:id' => 'politicos#show'
  
  get 'mapa'=> 'pages#mapa'
  get 'not_found'=> 'pages#not_found'
  
  get '401'=> 'pages#not_found'
  get '404'=> 'pages#not_found'
  get '422'=> 'pages#not_found'
  get '500'=> 'pages#not_found'
  

end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
    belongs_to :politico
    belongs_to :user
    validates :user,
           presence: true
    validates :politico,
           presence: true
    acts_as_votable
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :set_politico, only: [:create]
  before_action :set_comentario, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :authenticate_user!
  before_filter :require_permission, only: [:destroy]

  # GET /comentarios
  # GET /comentarios.json
  def index
    @comentarios = Comentario.order("created_at asc")
  end

  def upvote
    @comentario.upvote_by current_user
    redirect_to :back
  end
  def downvote
    @comentario.downvote_by current_user
    redirect_to :back
  end

  # GET /comentarios/1
  # GET /comentarios/1.json
  def show
  end

  # GET /comentarios/new
  def new
    @comentario = Comentario.new
  end

  # GET /comentarios/1/edit
  def edit
  end

  # POST /comentarios
  # POST /comentarios.json
  def create
    @comentario = @politico.comentarios.build(comentario_params)
    @comentario.user_id = current_user.id
    @comentario.save
    redirect_to @politico
  end

  # PATCH/PUT /comentarios/1
  # PATCH/PUT /comentarios/1.json
  def update
    respond_to do |format|
      if @comentario.update(comentario_params)
        format.html { redirect_to @comentario, notice: 'Comentario was successfully updated.' }
        format.json { render :show, status: :ok, location: @comentario }
      else
        format.html { render :edit }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1
  # DELETE /comentarios/1.json
  def destroy
    #Encontrando um comentário dentro do post.
    @comentario = @politico.comentarios.find(params[:id])
    @comentario.destroy
    redirect_to @politico
  end

  private
    # Use callbacks to share common setup or constraints between actions.
     def require_permission
      set_comentario
      @comentario = @politico.comentarios.find(params[:id])
      if (current_user != @politico.user) and (current_user != @comentario.user)
        flash[:notice] = 'Permissões insuficientes!'
        redirect_to @politico
      end
     end

    def set_politico
      @politico = Politico.find(params[:politico_id])
    end
    def set_comentario
      set_politico
      #@politico = Politico.find(params[:politico_id])
      @comentario = @politico.comentarios.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comentario_params
      params.require(:comentario).permit(:mensagem)
    end
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/views/comentarios/ _comentarios.html.erb
<table width="960" border="0" align="center">
  <tbody>
    <tr>
      <td align="center" valign="middle">
      
      <%= div_for(comentario) do %>
        <section class="content">
          <div class="container">
            <div class="col-sm-6 padd">
              <div class="owl-carousel owl-testimonial-default">
                <div class="item">
                  <blockquote class="testimonial">
                    <p><%= comentario.mensagem %></p>
                  </blockquote>
                  <div class="arrow-down"></div>
                  <div class="testimonial-info ">
                    <%=image_tag(comentario.user.photo.url(:thumb))%>
                    <div class="testimonial-author">
                      <h6>
                        <% if comentario.user == current_user %>
                          Você
                        <% else %>
                          <%= comentario.user.email %>
                        <%end%>
                      </h6>
                      Enviado há <strong><%= time_ago_in_words(comentario.created_at) %></strong>
                      <br>
                      <h6><% if user_signed_in? %>
                        <div class="btn-group">
                          <%= link_to like_politico_comentario_path(comentario.politico, comentario), method: :put, class: "btn pi-btn-green btn-default" do %>
                            <span class="glyphicon glyphicon-thumbs-up"></span>
                            <%= comentario.get_upvotes.size %>
                          <% end %>
                          <%= link_to dislike_politico_comentario_path(comentario.politico, comentario), method: :put, class: "btn pi-btn-red btn-default " do %>
                            <span class="glyphicon glyphicon-thumbs-down"></span>
                            <%= comentario.get_downvotes.size %>
                          <% end %>
                          <%if (current_user == comentario.politico.user) or (current_user == comentario.user)%>
                              <%= link_to [comentario.politico, comentario],
                                          method: :delete,
                                          class: "btn btn-warning",
                                          data: { confirm: "Tem certeza?"}  do %>
                              <span class=" glyphicon glyphicon-trash"></span>
                              <%end%>
                          <%end%>
                        </div>
                      <% end %></h6>
                    </div>
                  </div>
                  </div><!-- end testimonial-author -->
                </div><!-- end testimonial-info -->
                </div><!-- end item -->
              </div>
            </div>
          </div>
        </section>
    <% end %>
      
      
      
      
      </td>
    </tr>
  </tbody>
</table>

app/views/comentarios/_comentario.html.erb
<%= div_for(comentario)  do %>

                      <hr class="divider-big">
                      <a class="pull-left">
                              <%=image_tag(comentario.user.photo.url(:thumb), style:"width:65px;height:65px;")%>
                      </a>
                      <div class="media-body">
                          <h6 class="media-heading">
                            <% if comentario.user == current_user %>
                              &nbsp;&nbsp;&nbsp;Você
                            <% else %>
                              &nbsp;&nbsp;&nbsp;<%= comentario.user.email %>
                            <%end%>
                            <span class="pull-right">Há <%= time_ago_in_words(comentario.created_at) %>
                        <div class="btn-group">
                            <%= link_to like_politico_comentario_path(comentario.politico, comentario), method: :put, class: "btn pi-btn-green btn-default" do %>
                              <span class="glyphicon glyphicon-thumbs-up"></span>
                              <%= comentario.get_upvotes.size %>
                            <% end %>
                            <%= link_to dislike_politico_comentario_path(comentario.politico, comentario), method: :put, class: "btn pi-btn-red btn-default " do %>
                              <span class="glyphicon glyphicon-thumbs-down"></span>
                              <%= comentario.get_downvotes.size %>
                            <% end %>
                            <%if current_user == comentario.user%>
                              <div class="btn-group pull-right">
                                <%= link_to [comentario.politico, comentario],
                                            method: :delete,
                                            class: "btn btn-warning",
                                            data: { confirm: "Tem certeza?"}  do %>
                                              <span class=" glyphicon glyphicon-trash"></span>
                                            <%end%>
                              </div>
                            <%end%>
                        </div>
                         </span>
                                                 </h6>  
                          <p>&nbsp;&nbsp;&nbsp;<%= comentario.mensagem %></p>
                      </div>
<% end %>

app/views/comentarios/_comentarioz.html.erb
<table width="960" border="0" align="center">
  <tbody>
    <tr>
      <td align="center" valign="middle">
      
      <%= div_for(comentario) do %>
        <section class="content">
          <div class="container">
            <div class="col-sm-6 padd">
              <div class="owl-carousel owl-testimonial-default">
                <div class="item">
                  <blockquote class="testimonial">
                    <p><%= comentario.mensagem %><br></p>
                  </blockquote>
                  <div class="arrow-down"></div>
                  <div class="testimonial-info ">
                    <%=image_tag(comentario.user.photo.url(:thumb))%>
                    <div class="testimonial-author">
                      <h6>
                        <% if comentario.user == current_user %>
                          Você
                        <% else %>
                          <%= comentario.user.email %>
                        <%end%>
                      </h6>
                      Enviado há <strong><%= time_ago_in_words(comentario.created_at) %></strong>
                      <% if user_signed_in? %>
                        <div class="btn-group pull-right">
                          <%= link_to like_politico_comentario_path(comentario.politico, comentario), method: :put, class: "btn pi-btn-green btn-default" do %>
                            <span class="glyphicon glyphicon-thumbs-up"></span>
                            <%= comentario.get_upvotes.size %>
                          <% end %>
                          <%= link_to dislike_politico_comentario_path(comentario.politico, comentario), method: :put, class: "btn pi-btn-red btn-default " do %>
                            <span class="glyphicon glyphicon-thumbs-down"></span>
                            <%= comentario.get_downvotes.size %>
                          <% end %>
                          <%if (current_user == comentario.politico.user) or (current_user == comentario.user)%>
                            <div class="btn-group pull-right">
                              <%= link_to [comentario.politico, comentario],
                                          method: :delete,
                                          class: "btn btn-warning",
                                          data: { confirm: "Tem certeza?"}  do %>
                              <span class=" glyphicon glyphicon-trash"></span>
                              <%end%>
                            </div>
                          <%end%>
                        </div>
                      <% end %>
                    </div><!-- end testimonial-author -->
                  </div><!-- end testimonial-info -->
                </div><!-- end item -->
              </div>
            </div>
          </div>
        </section>
    <% end %>
      
      
      
      
      </td>
    </tr>
  </tbody>
</table>

app/views/comentarios/_form.html.erb
  <%= form_for([@politico, @politico.comentarios.build]) do |f| %>
  <div class="post-comment">
      <h5>Faça um comentário</h5>
      <form>
          <label>Mensagem:</label>
          <div class="row margin-bottom-20">
              <div class="col-md-11 col-md-offset-0">
                  <%= f.text_area :mensagem, class: "form-control" %>
              </div>                
          </div>
          
          <p><%= button_tag(type: "submit", class: "btn pi-btn-light-grey", name: "commit", value: "conceal") do %>
                        Enviar comentário
             <% end %></p>
      </form>
  </div>
 <%end%>

app/views/comentarios/edit.html.erb
<h1>Editing Comentario</h1>

<%= render 'form' %>

<%= link_to 'Show', @comentario %> |
<%= link_to 'Back', comentarios_path %>

app/views/comentarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comentarios</h1>

<table>
  <thead>
    <tr>
      <th>Mensagem</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comentarios.each do |comentario| %>
      <tr>
        <td><%= comentario.mensagem %></td>
        <td><%= comentario.politico %></td>
        <td><%= link_to 'Show', comentario %></td>
        <td><%= link_to 'Edit', edit_comentario_path(comentario) %></td>
        <td><%= link_to 'Destroy', comentario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comentario', new_comentario_path %>

app/views/comentarios/new.html.erb
<h1>New Comentario</h1>

<%= render 'form' %>

<%= link_to 'Back', comentarios_path %>

app/views/comentarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mensagem:</strong>
  <%= @comentario.mensagem %>
</p>

<p>
  <strong>Politico:</strong>
  <%= @comentario.politico %>
</p>

<%= link_to 'Edit', edit_comentario_path(@comentario) %> |
<%= link_to 'Back', comentarios_path %>