config/routes.rb
Rails.application.routes.draw do
  match '/contacts',     to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :cargos
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks"  }
  root to: "pages#home"

  resources :politicos do
      collection do
        match 'search' => 'politicos#search', via: [:get, :post], as: :search
      end
      member do
        put "like", to: "politicos#upvote"
        put "dislike", to: "politicos#downvote"
      end
      resources :comentarios do
        member do
              put "like", to: "comentarios#upvote"
              put "dislike", to: "comentarios#downvote"
        end
      end
      resources :acontecimentos do
        member do
          put "like", to: "acontecimentos#upvote"
          put "dislike", to: "acontecimentos#downvote"
        end
      end
  end
  
  resources :partidos
  
  get '/politicos/cargos/:nome' => 'politicos#show'
  get '/politicos/cargos/:nome/:estado' => 'politicos#show'
  get '/politicos/:id' => 'politicos#show'
  
  get 'mapa'=> 'pages#mapa'
  get 'not_found'=> 'pages#not_found'
  
  get '401'=> 'pages#not_found'
  get '404'=> 'pages#not_found'
  get '422'=> 'pages#not_found'
  get '500'=> 'pages#not_found'
  

end

app/models/politico.rb
class Politico < ActiveRecord::Base
  paginates_per 10
  belongs_to :partido
  belongs_to :user
  belongs_to :cargo
  has_many :comentarios
  has_many :acontecimentos
  has_attached_file :photo, styles: { medium: "600x400>", thumb: "150x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
  validates :photo, attachment_presence: true
  validates_with AttachmentSizeValidator, attributes: :photo, less_than: 5.megabytes
  acts_as_votable
end

app/controllers/politicos_controller.rb
class PoliticosController < ApplicationController
  before_action :set_politico, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  #Garantindo que somente o dono de um Post pode executar as ações de edit, update e destroy
  before_filter :require_permission, only: [:edit, :update, :destroy]

  def home
    render :layout => 'landing'
  end

  def mapa
    render "mapa"
  end

  
  def upvote
    @politico.upvote_by current_user
    redirect_to :back
  end
  def downvote
    @politico.downvote_from current_user
    redirect_to :back
  end
  
  def search
    busca
    render :show
  end

  # GET /politicos
  # GET /politicos.json
  def index
    @q = Politico.search(params[:q])
    @politicos = @q.result(distinct: true)
  end
  
  def busca
    @q = Politico.search(params[:q])
    @politico = @q.result(distinct: true).first
  end

  # GET /politicos/1
  # GET /politicos/1.json
  def show
  end


  # GET /politicos/new
  def new
    @politico = current_user.politicos.build
  end

  # GET /politicos/1/edit
  def edit
  end

  # POST /politicos
  # POST /politicos.json
  def create
    @politico = current_user.politicos.build(politico_params)

    respond_to do |format|
      if @politico.save
        format.html { redirect_to @politico, notice: 'Politico was successfully created.' }
        format.json { render :show, status: :created, location: @politico }
      else
        format.html { render :new }
        format.json { render json: @politico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /politicos/1
  # PATCH/PUT /politicos/1.json
  def update
    respond_to do |format|
      if @politico.update(politico_params)
        format.html { redirect_to @politico, notice: 'Politico was successfully updated.' }
        format.json { render :show, status: :ok, location: @politico }
      else
        format.html { render :edit }
        format.json { render json: @politico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /politicos/1
  # DELETE /politicos/1.json
  def destroy
    @politico.destroy
    respond_to do |format|
      format.html { redirect_to politicos_url, notice: 'Politico was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def require_permission
      if current_user != Politico.find(params[:id]).user
        flash[:notice] = 'Permissões insuficientes!'
        redirect_to root_path
      end
    end
    def set_cargo
      @cargo = Cargo.where(nome: params[:nome]).first
    end
    def set_politico
      set_cargo
      if !@cargo.nil?
        id = 0
        id = @cargo.id.to_i
        if (@cargo.id && params[:estado])  
            @politico = Politico.find_by_sql(["SELECT * FROM politicos where cargo_id = ? and estado = ?", id, params[:estado]]).first
          else
          if (@cargo.nome)
              @politico = Politico.find_by_sql(["SELECT * FROM politicos where cargo_id = ?", id]).first
          end
        end
      else
          @politico = Politico.find(params[:id])
      end
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def politico_params
      params.require(:politico).permit(:nome, :idade, :estado, :cidade, :municipio, :partido_id, :cargo_id, :status, :photo, :user_id)
    end
end

app/helpers/politicos_helper.rb
module PoliticosHelper
end

app/views/politicos/_form.html.erb
<%= form_for(@politico) do |f| %>
  <% if @politico.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@politico.errors.count, "error") %> prohibited this politico from being saved:</h2>

      <ul>
      <% @politico.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :idade %><br>
    <%= f.number_field :idade %>
  </div>
  <div class="field">
    <%= f.label :estado %><br>
    <%= f.text_field :estado %>
  </div>
  <div class="field">
    <%= f.label :cidade %><br>
    <%= f.text_field :cidade %>
  </div>
  <div class="field">
    <%= f.label :municipio %><br>
    <%= f.text_field :municipio %>
  </div>
  <div class="field">
    <%= f.label :partido_id %><br>
    <%= f.text_field :partido_id %>
  </div>
  <div class="field">
    <%= f.label :cargo_eleito %><br>
    <%= f.text_field :cargo_eleito %>
  </div>
  <div class="field">
    <%= f.label :cargo_atual %><br>
    <%= f.text_field :cargo_atual %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label "Foto" %><br>
    <%= f.file_field :photo, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/politicos/edit.html.erb
<h1>Editing Politico</h1>

<%= render 'form' %>

<%= link_to 'Show', @politico %> |
<%= link_to 'Back', politicos_path %>

app/views/politicos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Politicos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Idade</th>
      <th>Estado</th>
      <th>Cidade</th>
      <th>Municipio</th>
      <th>Partido</th>
      <th>Cargo eleito</th>
      <th>Cargo atual</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @politicos.each do |politico| %>
      <tr>
        <td><%= politico.nome %></td>
        <td><%= politico.idade %></td>
        <td><%= politico.estado %></td>
        <td><%= politico.cidade %></td>
        <td><%= politico.municipio %></td>
        <td><%= politico.partido.nome %></td>
        <td><%= politico.status %></td>
        <td><%= link_to 'Show', politico %></td>
        <td><%= link_to 'Edit', edit_politico_path(politico) %></td>
        <td><%= link_to 'Destroy', politico, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% @politicos.each do |politico| %>
   <li><%= politico.nome %></li>
 <% end %>

<%= link_to 'New Politico', new_politico_path %>

app/views/politicos/new.html.erb
<h1>New Politico</h1>

<%= render 'form' %>

<%= link_to 'Back', politicos_path %>

app/views/politicos/show.html.erb
<%= div_for(@politico) do %>
<%titulo = "" %>
<% titulo = @politico.nome %>
<% @title=titulo %>
<% case @politico.cargo_id
     when 1 %>
      <header id="header" class="section-parallax parallaxBg" style="background-image: url(/img/palacio-do-planalto-21.jpg);">
     <% when 2   
       case @politico.estado.downcase
         when "rj" %>
           <header id="header" class="section-parallax parallaxBg" style="background-image: url(/img/guanabara.jpg);">
         <% when "sp" %>
           <header id="header" class="section-parallax parallaxBg" style="background-image: url(/img/bandeirantes.jpg);">
       <% else %>
         <header id="header" class="section-parallax parallaxBg" style="background-image: url(/img/bandeirantes.jpg);">
       <% end %>
<% else %>
  <header id="header" class="section-parallax parallaxBg" style="background-image: url(/img/bandeirantes.jpg);">
<% end %>
    	<div class="layer"></div>
        <div class="container parallax-content text-center">
        	<section class="home section-parallax parallaxBg">
          	<div class="container">
              	<div class="row">
                  	<div class="col-sm-12 col-md-5 padd">
                          <div class="owl-carousel owl-item-1">
      
                              <div class="item" data-no-turbolink>
                                <%= image_tag(@politico.photo.url(:medium)) %>
                              </div>
      
                          </div><!-- end owl-item-1 -->
                      </div>
                      
                      <div class="col-sm-12 col-md-7 padd">
                      	<h5><%= @politico.nome %></h5>
                          <div class="line"></div>
                          <% if @politico.cargo_id != 2 %>
                            <em> Vice: <%= @politico.vice %></em>
                          <% end %>
      					          <p> <%= @politico.descricao %></p>
                          <ul class="list1">
                              <li class="wow fadeInDown" data-wow-duration="1s"><i></i><%= @politico.status %></li>
                              <li class="wow fadeInDown" data-wow-duration="2s"><i></i>Natural de <%= @politico.cidade %> </li>
                              <li class="wow fadeInDown" data-wow-duration="3s"><i></i><%= image_tag(@politico.partido.photo.url(:thumb)) %></li>
                          </ul>
                      </div>
                  </div><!-- end row -->
              </div><!-- end container -->
            </section>
        </div><!-- end container -->
    </header>
    <br>
    <% c=@politico.acontecimentos.count %>
    <% if c > 0 %>
      <div class="container" >
        <div class="row ">
          <div class="col-md-offset-2 col-md-8 col-sm-12 top-margin" >
            <div >
              <ul class="timeline">
                <li class="time-label">
                                      <span class="bg-orange">Acontecimentos Marcantes
                                      </span>
                  <br />
                  <br />
                </li>
                <li class="time-label">
                  <span class="bg-light-blue"> 2016
                  </span>
                </li>
                <%= render @politico.acontecimentos.order(data_pub: :desc) %>
                </ul>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    
    
    <section class="content">
    	<div class="container">
        	<div class="row">
                <div class="col-sm-12 blog-container margin-top-40">
                    <div class="media">
                      <hr class="divider-dotted divider-big" />
                        <h5><% c=@politico.comentarios.count %>
                            <%if c > 0 %>
                                <%= c %>
                                <% if c > 1 %>
                                    comentários
                                <% else %>
                                    comentário
                                <% end %>
                            <%else%>
                                Sem comentários
                            <%end%>
                        </h5>
  
                        <%= render @politico.comentarios.reverse, review: Comentario.new(politico_id: @politico.id) %>
                    </div>
                    <%= render "comentarios/form" %>
                  </div>
                </div>
              </div>
            </section>
<% end %>