config/routes.rb
Rails.application.routes.draw do
  match '/contacts',     to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :cargos
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks"  }
  root to: "pages#home"

  resources :politicos do
      collection do
        match 'search' => 'politicos#search', via: [:get, :post], as: :search
      end
      member do
        put "like", to: "politicos#upvote"
        put "dislike", to: "politicos#downvote"
      end
      resources :comentarios do
        member do
              put "like", to: "comentarios#upvote"
              put "dislike", to: "comentarios#downvote"
        end
      end
      resources :acontecimentos do
        member do
          put "like", to: "acontecimentos#upvote"
          put "dislike", to: "acontecimentos#downvote"
        end
      end
  end
  
  resources :partidos
  
  get '/politicos/cargos/:nome' => 'politicos#show'
  get '/politicos/cargos/:nome/:estado' => 'politicos#show'
  get '/politicos/:id' => 'politicos#show'
  
  get 'mapa'=> 'pages#mapa'
  get 'not_found'=> 'pages#not_found'
  
  get '401'=> 'pages#not_found'
  get '404'=> 'pages#not_found'
  get '422'=> 'pages#not_found'
  get '500'=> 'pages#not_found'
  

end

app/models/acontecimento.rb
class Acontecimento < ActiveRecord::Base
    belongs_to :politico
    acts_as_votable
end

app/controllers/acontecimentos_controller.rb
class AcontecimentosController < ApplicationController
  before_action :set_politico, only: [:create]
  before_action :set_acontecimento, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :authenticate_user!


  # GET /acontecimentos
  # GET /acontecimentos.json
  def index
    @acontecimentos = Acontecimento.order(data_pub: :desc)
  end
  
  def upvote
    @acontecimento.upvote_by current_user
    redirect_to :back
end
  end
  def downvote
    @acontecimento.downvote_from current_user
    redirect_to :back
  end

  # GET /acontecimentos/1
  # GET /acontecimentos/1.json
  def show
  end

  # GET /acontecimentos/new
  def new
    @acontecimento = Acontecimento.new
  end

  # GET /acontecimentos/1/edit
  def edit
  end

  # POST /acontecimentos
  # POST /acontecimentos.json
  def create
    #Construção de um comentário dentro do post.
    @acontecimento = @politico.acontecimento.build(acontecimento_params)
    @acontecimento.save
    redirect_to @politico

    respond_to do |format|
      if @acontecimento.save
        format.html { redirect_to @acontecimento, notice: 'Acontecimento was successfully created.' }
        format.json { render :show, status: :created, location: @acontecimento }
      else
        format.html { render :new }
        format.json { render json: @acontecimento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /acontecimentos/1
  # PATCH/PUT /acontecimentos/1.json
  def update
    respond_to do |format|
      if @acontecimento.update(acontecimento_params)
        format.html { redirect_to @acontecimento, notice: 'Acontecimento was successfully updated.' }
        format.json { render :show, status: :ok, location: @acontecimento }
      else
        format.html { render :edit }
        format.json { render json: @acontecimento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /acontecimentos/1
  # DELETE /acontecimentos/1.json
  def destroy
    #Encontrando um comentário dentro do post.
    @acontecimento = @politico.comments.find(params[:id])
    @acontecimento.destroy
    redirect_to @politico
    respond_to do |format|
      format.html { redirect_to acontecimentos_url, notice: 'Acontecimento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_politico
      @politico = Politico.find(params[:politico_id])
    end
    def set_acontecimento
      set_politico
      @acontecimento = @politico.acontecimentos.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def acontecimento_params
      params.require(:acontecimento).permit(:titulo, :descricao, :link, :photo)
    end
end

app/helpers/acontecimentos_helper.rb
module AcontecimentosHelper
end

app/views/acontecimentos/_acontecimento.html.erb
          <% if acontecimento.data_pub.strftime("%Y") == 2016 %>
          <li class="time-label">
                                <span class="bg-light-blue"> <%= acontecimento.data_pub.strftime("%Y") %>
                                </span>
          </li>
          <% end %>
          <li>
            <i class="fa fa-envelope bg-blue"></i>
            <div class="timeline-item">
              <span class="time"><i class="fa fa-clock-o"></i><%= acontecimento.data_pub.strftime("%d/%m/%Y") %></span>
              <h3 class="timeline-header"> <%=link_to acontecimento.titulo,"http://#{acontecimento.link}", :target => "_blank"%> </h3>
              <div class="timeline-body" style="background-color:">
                   <%= acontecimento.descricao %>
              </div>
              <div class='timeline-footer'>
                <a class="btn btn-primary btn-xs" href="https://twitter.com/share"
                data-size="large"
                data-url="<%= request.original_url%>"
                data-via="waltersfilho"
                data-related="politica,twitter"
                data-hashtags="memoriadeelefante"
                data-text="<%=acontecimento.titulo%>" to_see_on_twitter target="_blank">Compartilhar no Twitter</a>
                <a class="btn btn-primary btn-xs" href="https://www.facebook.com/sharer/sharer.php?u=<%=request.original_url%>" target="_blank">Compartilhar no Facebook</a>
                <%= link_to like_politico_acontecimento_path(acontecimento.politico, acontecimento), method: :put, class: "btn pi-btn-green btn-xs pull-center" do %>
                    Curtir
                    <span class="glyphicon glyphicon-thumbs-up text-center" aria-hidden="true"></span>
                    <%= acontecimento.get_upvotes.size %>
                <% end %>
                <%= link_to dislike_politico_acontecimento_path(acontecimento.politico, acontecimento), method: :put, class: "btn pi-btn-red btn-xs pull-center" do %>
                    Descurtir
                    <span class="glyphicon glyphicon-thumbs-down text-center" aria-hidden="true"></span>
                    <%= acontecimento.get_downvotes.size %>
                <% end %>
                <% case acontecimento.link.at(4..5) %>
                    <% when "g1" %>
                    <small style="float:right"> Fonte: G1 </small>
                    <% when "gl" %>
                    <small style="float:right"> Fonte: Globo.com </small>
                    <% when "og" %>
                    <small style="float:right"> Fonte: Jornal O Globo </small>
                    <% when "ca" %>
                    <small style="float:right"> Fonte: Carta Capital</small>
                    <% when "co" %>
                    <small style="float:right"> Fonte: Correio do Brasil</small>
                    <% when "li" %>
                    <small style="float:right"> Fonte: ZH Política</small>
                    <% when "ci" %>
                    <small style="float:right"> Fonte: Terra</small>
                    <% when "fo" %>
                    <small style="float:right"> Fonte: Folha de São Paulo</small>
                    <% else %>
                    <small style="float:right"> Fonte: Desconhecida </small>
                <% end %>
              </div>
            </div>
          </li>
          <script src='http://connect.facebook.net/pt_BR/all.js'></script>
            <p><a onclick='postToFeed(); return false;'></a></p>
            <p id='msg'></p>
        
            <script> 
              FB.init({appId: "544616482377018", status: true, cookie: true});
        
              function postToFeed() {
        
                // calling the API ...
                var obj = {
                  method: 'feed',
                  redirect_uri:'https://www.facebook.com/cryswashington?fref=ts',
                  link:'https://developers.facebook.com/docs/reference/dialogs/',
                  picture: 'http://fbrell.com/f8.jpg',
                  name: 'Facebook Dialogs',
                  caption: 'Reference Documentation',
                  description: '<%= acontecimento.descricao %>'
                };
        
                function callback(response) {
        
                document.getElementById('msg').innerHTML = "Post ID: " + response['post_id'];
                }
        
                FB.ui(obj, callback);
              }
              
              

    </script>
    <script type="text/javascript">
      $(document).on('ready page:change', function() {
        $("meta[name='twitter\\:title']").attr("content", "<%= acontecimento.titulo %>");
        $("meta[name='twitter\\:description']").attr("content", "<%= acontecimento.descricao %>");
        $("meta[name='twitter\\:image']").attr("content", "<%= @politico.photo %>");
        $("meta[property='og\\:title']").attr("content", "<%= acontecimento.titulo %>");
        $("meta[property='og\\:description']").attr("content", "<%= acontecimento.descricao %>");
        $("meta[property='og\\:url']").attr("content", "<%= request.original_url %>");
        $("meta[property='og\\:image']").attr("content", "<%= @politico.photo %>");
      });
</script>

app/views/acontecimentos/_form.html.erb
<%= form_for([@politico, @politico.acontecimentos.build]) do |f| %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br>
    <%= f.text_field :descricao %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/acontecimentos/edit.html.erb
<h1>Editing Acontecimento</h1>

<%= render 'form' %>

<%= link_to 'Show', @acontecimento %> |
<%= link_to 'Back', acontecimentos_path %>

app/views/acontecimentos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Acontecimentos</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Descricao</th>
      <th>Link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @acontecimentos.each do |acontecimento| %>
      <tr>
        <td><%= acontecimento.titulo %></td>
        <td><%= acontecimento.descricao %></td>
        <td><%= acontecimento.link %></td>
        <td><%= link_to 'Show', acontecimento %></td>
        <td><%= link_to 'Edit', edit_acontecimento_path(acontecimento) %></td>
        <td><%= link_to 'Destroy', acontecimento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Acontecimento', new_acontecimento_path %>

app/views/acontecimentos/new.html.erb
<h1>New Acontecimento</h1>

<%= render 'form' %>

<%= link_to 'Back', acontecimentos_path %>

app/views/acontecimentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @acontecimento.titulo %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @acontecimento.descricao %>
</p>

<p>
  <strong>Link:</strong>
  <%= @acontecimento.link %>
</p>

<%= link_to 'Edit', edit_acontecimento_path(@acontecimento) %> |
<%= link_to 'Back', acontecimentos_path %>